apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default  # Change as needed
  annotations:
    avp.kubernetes.io/path: "kv/data/db"
type: Opaque
stringData:
  db_username: <db_username>
  db_password: <db_password>
  db_name: <db_name>
