apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default  # Change as needed
  annotations:
    avp.kubernetes.io/path: "kv/data/db"
type: Opaque
stringData:
  username: <username>
  password: <password>
